name: Deploy

on:
  push:
    branches:
      - online

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Archive built artifacts
      run: (cd dist && tar czf site.tgz ./*)

    - name: Install SSH private key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_FINGERPRINT: ${{ secrets.DEPLOY_FINGERPRINT }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "$DEPLOY_FINGERPRINT" >> ~/.ssh/known_hosts

    - name: Deploy
      env:
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        DEPLOY_DIR: ${{ secrets.DEPLOY_DIR }}
      run: |
        scp dist/site.tgz $DEPLOY_USER@$DEPLOY_HOST:~
        ssh $DEPLOY_USER@$DEPLOY_HOST "cd $DEPLOY_DIR && rm -rf ./* && tar xf ~/site.tgz && rm ~/site.tgz"
